export type Category = 'CAPITAL' | 'LANDMARK' | 'ANIMAL' | 'FOOD' | 'FLAG' | 'GESTURE_BONUS';
export type Difficulty = 1 | 2 | 3;

export interface Question {
  id: string;
  category: Category;
  country: string;
  flag: string;
  destination: string;
  bgFrom: string;
  bgTo: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  difficulty: Difficulty;
  emoji?: string;
}

export interface GestureBonusQuestion {
  id: string;
  category: 'GESTURE_BONUS';
  instruction: string;
  requiredGesture: string;
  emoji: string;
  points: number;
}

const questions: Question[] = [
  // === CAPITALS ===
  {
    id: 'cap-jp',
    category: 'CAPITAL',
    country: 'Japan',
    flag: '🇯🇵',
    destination: 'Japan',
    bgFrom: '#bc0004',
    bgTo: '#ff6b6b',
    question: 'What is the capital of Japan?',
    options: ['Tokyo', 'Seoul', 'Beijing', 'Bangkok'],
    correctIndex: 0,
    explanation: 'Tokyo is the capital and largest city of Japan, home to over 14 million people!',
    difficulty: 1,
    emoji: '🗼',
  },
  {
    id: 'cap-fr',
    category: 'CAPITAL',
    country: 'France',
    flag: '🇫🇷',
    destination: 'France',
    bgFrom: '#003189',
    bgTo: '#ef4444',
    question: 'What is the capital of France?',
    options: ['Lyon', 'Marseille', 'Paris', 'Nice'],
    correctIndex: 2,
    explanation: 'Paris, the "City of Light," is the capital of France and home to the Eiffel Tower!',
    difficulty: 1,
    emoji: '🗼',
  },
  {
    id: 'cap-br',
    category: 'CAPITAL',
    country: 'Brazil',
    flag: '🇧🇷',
    destination: 'Brazil',
    bgFrom: '#009c3b',
    bgTo: '#ffdf00',
    question: 'What is the capital of Brazil?',
    options: ['São Paulo', 'Rio de Janeiro', 'Salvador', 'Brasília'],
    correctIndex: 3,
    explanation: 'Brasília! Many people think it\'s Rio de Janeiro, but Brasília became the capital in 1960.',
    difficulty: 2,
    emoji: '🌴',
  },
  {
    id: 'cap-au',
    category: 'CAPITAL',
    country: 'Australia',
    flag: '🇦🇺',
    destination: 'Australia',
    bgFrom: '#00008b',
    bgTo: '#ff3333',
    question: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctIndex: 2,
    explanation: 'Canberra! Sydney is more famous, but Canberra was purpose-built to be Australia\'s capital city.',
    difficulty: 2,
    emoji: '🦘',
  },
  {
    id: 'cap-eg',
    category: 'CAPITAL',
    country: 'Egypt',
    flag: '🇪🇬',
    destination: 'Egypt',
    bgFrom: '#c09000',
    bgTo: '#8b4513',
    question: 'What is the capital of Egypt?',
    options: ['Alexandria', 'Cairo', 'Luxor', 'Aswan'],
    correctIndex: 1,
    explanation: 'Cairo is the capital of Egypt and the largest city in Africa! It sits near the ancient Pyramids of Giza.',
    difficulty: 1,
    emoji: '🐪',
  },
  {
    id: 'cap-cn',
    category: 'CAPITAL',
    country: 'China',
    flag: '🇨🇳',
    destination: 'China',
    bgFrom: '#de2910',
    bgTo: '#ffde00',
    question: 'What is the capital of China?',
    options: ['Shanghai', 'Hong Kong', 'Beijing', 'Guangzhou'],
    correctIndex: 2,
    explanation: 'Beijing has been China\'s capital for over 600 years and is home to the Forbidden City!',
    difficulty: 1,
    emoji: '🐉',
  },
  {
    id: 'cap-ca',
    category: 'CAPITAL',
    country: 'Canada',
    flag: '🇨🇦',
    destination: 'Canada',
    bgFrom: '#ff0000',
    bgTo: '#8b0000',
    question: 'What is the capital of Canada?',
    options: ['Toronto', 'Vancouver', 'Montreal', 'Ottawa'],
    correctIndex: 3,
    explanation: 'Ottawa! Toronto is the largest city, but Ottawa has been Canada\'s capital since 1867.',
    difficulty: 2,
    emoji: '🍁',
  },
  {
    id: 'cap-in',
    category: 'CAPITAL',
    country: 'India',
    flag: '🇮🇳',
    destination: 'India',
    bgFrom: '#ff9933',
    bgTo: '#138808',
    question: 'What is the capital of India?',
    options: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'],
    correctIndex: 1,
    explanation: 'New Delhi is the capital of India and home to Parliament House and many historic monuments!',
    difficulty: 1,
    emoji: '🕌',
  },
  {
    id: 'cap-mx',
    category: 'CAPITAL',
    country: 'Mexico',
    flag: '🇲🇽',
    destination: 'Mexico',
    bgFrom: '#006847',
    bgTo: '#ce1126',
    question: 'What is the capital of Mexico?',
    options: ['Guadalajara', 'Cancún', 'Mexico City', 'Monterrey'],
    correctIndex: 2,
    explanation: 'Mexico City! It\'s one of the largest cities in the world, built on the ancient Aztec city of Tenochtitlan.',
    difficulty: 1,
    emoji: '🌮',
  },
  {
    id: 'cap-sa',
    category: 'CAPITAL',
    country: 'South Africa',
    flag: '🇿🇦',
    destination: 'South Africa',
    bgFrom: '#007a4d',
    bgTo: '#ffb612',
    question: 'What is the legislative capital of South Africa?',
    options: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria'],
    correctIndex: 1,
    explanation: 'Cape Town is the legislative capital! South Africa actually has three capitals — a very unique arrangement.',
    difficulty: 3,
    emoji: '🦁',
  },
  {
    id: 'cap-it',
    category: 'CAPITAL',
    country: 'Italy',
    flag: '🇮🇹',
    destination: 'Italy',
    bgFrom: '#009246',
    bgTo: '#ce2b37',
    question: 'What is the capital of Italy?',
    options: ['Milan', 'Venice', 'Florence', 'Rome'],
    correctIndex: 3,
    explanation: 'Rome! The Eternal City has been a center of civilization for over 2,500 years!',
    difficulty: 1,
    emoji: '🍕',
  },
  {
    id: 'cap-arg',
    category: 'CAPITAL',
    country: 'Argentina',
    flag: '🇦🇷',
    destination: 'Argentina',
    bgFrom: '#74acdf',
    bgTo: '#ffffff',
    question: 'What is the capital of Argentina?',
    options: ['Córdoba', 'Rosario', 'Buenos Aires', 'Mendoza'],
    correctIndex: 2,
    explanation: 'Buenos Aires means "fair winds" in Spanish and is called the "Paris of South America"!',
    difficulty: 1,
    emoji: '💃',
  },
  {
    id: 'cap-gr',
    category: 'CAPITAL',
    country: 'Greece',
    flag: '🇬🇷',
    destination: 'Greece',
    bgFrom: '#0d5eaf',
    bgTo: '#ffffff',
    question: 'What is the capital of Greece?',
    options: ['Thessaloniki', 'Athens', 'Heraklion', 'Patras'],
    correctIndex: 1,
    explanation: 'Athens is one of the world\'s oldest cities, birthplace of democracy and the Olympic Games!',
    difficulty: 1,
    emoji: '🏛️',
  },
  {
    id: 'cap-th',
    category: 'CAPITAL',
    country: 'Thailand',
    flag: '🇹🇭',
    destination: 'Thailand',
    bgFrom: '#a51931',
    bgTo: '#2d2a4a',
    question: 'What is the capital of Thailand?',
    options: ['Chiang Mai', 'Phuket', 'Bangkok', 'Pattaya'],
    correctIndex: 2,
    explanation: 'Bangkok! Its ceremonial full name is the longest place name in the world — 169 characters long!',
    difficulty: 1,
    emoji: '🐘',
  },
  {
    id: 'cap-ke',
    category: 'CAPITAL',
    country: 'Kenya',
    flag: '🇰🇪',
    destination: 'Kenya',
    bgFrom: '#006600',
    bgTo: '#cc0000',
    question: 'What is the capital of Kenya?',
    options: ['Mombasa', 'Kisumu', 'Nairobi', 'Nakuru'],
    correctIndex: 2,
    explanation: 'Nairobi is the capital of Kenya and is known as the "Green City in the Sun"!',
    difficulty: 2,
    emoji: '🦒',
  },

  // === LANDMARKS ===
  {
    id: 'land-cn',
    category: 'LANDMARK',
    country: 'China',
    flag: '🇨🇳',
    destination: 'China',
    bgFrom: '#8b0000',
    bgTo: '#ff6b35',
    question: 'Which famous wall stretches across northern China?',
    options: ['The Berlin Wall', 'The Great Wall', 'The Hadrian\'s Wall', 'The Aurelian Wall'],
    correctIndex: 1,
    explanation: 'The Great Wall of China is over 13,000 miles long and was built over many centuries to protect China from invasions!',
    difficulty: 1,
    emoji: '🧱',
  },
  {
    id: 'land-pe',
    category: 'LANDMARK',
    country: 'Peru',
    flag: '🇵🇪',
    destination: 'Peru',
    bgFrom: '#d91023',
    bgTo: '#c09000',
    question: 'What ancient Incan citadel is found in Peru?',
    options: ['Chichen Itza', 'Machu Picchu', 'Teotihuacan', 'Tikal'],
    correctIndex: 1,
    explanation: 'Machu Picchu is a 15th-century Incan citadel high in the Andes Mountains, one of the New Seven Wonders of the World!',
    difficulty: 1,
    emoji: '🏔️',
  },
  {
    id: 'land-jo',
    category: 'LANDMARK',
    country: 'Jordan',
    flag: '🇯🇴',
    destination: 'Jordan',
    bgFrom: '#007a3d',
    bgTo: '#ce1126',
    question: 'What ancient city carved into pink sandstone cliffs is in Jordan?',
    options: ['Palmyra', 'Petra', 'Leptis Magna', 'Ephesus'],
    correctIndex: 1,
    explanation: 'Petra, known as the "Rose City," was carved into pink sandstone cliffs by the Nabataean people over 2,000 years ago!',
    difficulty: 2,
    emoji: '🏜️',
  },
  {
    id: 'land-in',
    category: 'LANDMARK',
    country: 'India',
    flag: '🇮🇳',
    destination: 'India',
    bgFrom: '#ff6b00',
    bgTo: '#c09000',
    question: 'Which famous marble mausoleum is located in Agra, India?',
    options: ['Angkor Wat', 'Hagia Sophia', 'Taj Mahal', 'Red Fort'],
    correctIndex: 2,
    explanation: 'The Taj Mahal was built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal. It took 22 years to build!',
    difficulty: 1,
    emoji: '🕌',
  },
  {
    id: 'land-au',
    category: 'LANDMARK',
    country: 'Australia',
    flag: '🇦🇺',
    destination: 'Australia',
    bgFrom: '#012169',

    bgTo: '#e8112d',
    question: 'What iconic opera house is located in Sydney, Australia?',
    options: ['Royal Opera House', 'Sydney Opera House', 'Vienna State Opera', 'La Scala'],
    correctIndex: 1,
    explanation: 'The Sydney Opera House is one of the world\'s most famous buildings, recognized by UNESCO as a World Heritage Site!',
    difficulty: 1,
    emoji: '🎭',
  },
  {
    id: 'land-eg',
    category: 'LANDMARK',
    country: 'Egypt',
    flag: '🇪🇬',
    destination: 'Egypt',
    bgFrom: '#f4c430',
    bgTo: '#8b4513',
    question: 'In which country can you find the Great Pyramid of Giza?',
    options: ['Sudan', 'Morocco', 'Egypt', 'Libya'],
    correctIndex: 2,
    explanation: 'The Great Pyramid of Giza in Egypt was built around 2560 BC and is the oldest of the Seven Wonders of the Ancient World!',
    difficulty: 1,
    emoji: '🔺',
  },
  {
    id: 'land-us',
    category: 'LANDMARK',
    country: 'United States',
    flag: '🇺🇸',
    destination: 'United States',
    bgFrom: '#002868',
    bgTo: '#bf0a30',
    question: 'The Statue of Liberty was a gift from which country?',
    options: ['France', 'United Kingdom', 'Italy', 'Spain'],
    correctIndex: 0,
    explanation: 'France gave the Statue of Liberty to the United States in 1886 as a symbol of friendship and freedom!',
    difficulty: 2,
    emoji: '🗽',
  },

  // === ANIMALS ===
  {
    id: 'anim-au',
    category: 'ANIMAL',
    country: 'Australia',
    flag: '🇦🇺',
    destination: 'Australia',
    bgFrom: '#4a7c59',
    bgTo: '#c09000',
    question: 'Which marsupial carries its baby in a pouch and is native to Australia?',
    options: ['Lemur', 'Opossum', 'Kangaroo', 'Wallaby'],
    correctIndex: 2,
    explanation: 'Kangaroos are unique to Australia! Baby kangaroos (called joeys) live in their mother\'s pouch for about 6 months!',
    difficulty: 1,
    emoji: '🦘',
  },
  {
    id: 'anim-cn',
    category: 'ANIMAL',
    country: 'China',
    flag: '🇨🇳',
    destination: 'China',
    bgFrom: '#228b22',
    bgTo: '#1a1a1a',
    question: 'Which black-and-white bear is native to China and eats mainly bamboo?',
    options: ['Polar Bear', 'Giant Panda', 'Spectacled Bear', 'Sun Bear'],
    correctIndex: 1,
    explanation: 'The Giant Panda lives in mountain forests in central China. They eat up to 38 pounds of bamboo every day!',
    difficulty: 1,
    emoji: '🐼',
  },
  {
    id: 'anim-af',
    category: 'ANIMAL',
    country: 'Africa',
    flag: '🌍',
    destination: 'Africa',
    bgFrom: '#d4af37',
    bgTo: '#8b4513',
    question: 'Which African animal is the tallest land animal on Earth?',
    options: ['Elephant', 'Giraffe', 'Hippopotamus', 'Rhinoceros'],
    correctIndex: 1,
    explanation: 'Giraffes can grow up to 18 feet tall! Their long necks help them reach leaves in tall acacia trees.',
    difficulty: 1,
    emoji: '🦒',
  },
  {
    id: 'anim-bz',
    category: 'ANIMAL',
    country: 'Brazil',
    flag: '🇧🇷',
    destination: 'Amazon',
    bgFrom: '#006400',
    bgTo: '#228b22',
    question: 'Which colorful macaw is native to the Amazon rainforest?',
    options: ['Bald Eagle', 'Scarlet Macaw', 'Snow Owl', 'Toucan'],
    correctIndex: 1,
    explanation: 'The Scarlet Macaw is one of the most beautiful birds in the Amazon! They can live up to 75 years.',
    difficulty: 2,
    emoji: '🦜',
  },
  {
    id: 'anim-ar',
    category: 'ANIMAL',
    country: 'Arctic',
    flag: '🏔️',
    destination: 'The Arctic',
    bgFrom: '#4fc3f7',
    bgTo: '#ffffff',
    question: 'Which large white bear lives in the Arctic?',
    options: ['Grizzly Bear', 'Polar Bear', 'Kodiak Bear', 'Panda Bear'],
    correctIndex: 1,
    explanation: 'Polar bears are excellent swimmers and can swim for days at a time to find food. Their fur is actually transparent!',
    difficulty: 1,
    emoji: '🐻‍❄️',
  },
  {
    id: 'anim-in',
    category: 'ANIMAL',
    country: 'India',
    flag: '🇮🇳',
    destination: 'India',
    bgFrom: '#ff6600',
    bgTo: '#1a472a',
    question: 'Which big cat is the national animal of India?',
    options: ['Lion', 'Cheetah', 'Bengal Tiger', 'Leopard'],
    correctIndex: 2,
    explanation: 'The Bengal Tiger is India\'s national animal. India has more wild tigers than any other country in the world!',
    difficulty: 1,
    emoji: '🐯',
  },
  {
    id: 'anim-ke',
    category: 'ANIMAL',
    country: 'Kenya',
    flag: '🇰🇪',
    destination: 'Kenyan Savanna',
    bgFrom: '#c8a020',
    bgTo: '#8b4513',
    question: 'Which big cat is the fastest land animal on Earth?',
    options: ['Lion', 'Leopard', 'Jaguar', 'Cheetah'],
    correctIndex: 3,
    explanation: 'Cheetahs can run up to 70 mph (112 km/h)! They are found mainly in Africa and are the fastest land animals.',
    difficulty: 1,
    emoji: '🐆',
  },

  // === FOOD ===
  {
    id: 'food-it',
    category: 'FOOD',
    country: 'Italy',
    flag: '🇮🇹',
    destination: 'Italy',
    bgFrom: '#009246',
    bgTo: '#ce2b37',
    question: 'Which Italian dish is a flatbread topped with tomato sauce and cheese?',
    options: ['Paella', 'Pizza', 'Crepe', 'Tortilla'],
    correctIndex: 1,
    explanation: 'Pizza originated in Naples, Italy! The word "pizza" first appeared in a Latin text from 997 AD.',
    difficulty: 1,
    emoji: '🍕',
  },
  {
    id: 'food-jp',
    category: 'FOOD',
    country: 'Japan',
    flag: '🇯🇵',
    destination: 'Japan',
    bgFrom: '#bc0004',
    bgTo: '#ff9999',
    question: 'Which Japanese food consists of vinegared rice with fish or vegetables?',
    options: ['Ramen', 'Tempura', 'Sushi', 'Udon'],
    correctIndex: 2,
    explanation: 'Sushi has been part of Japanese cuisine for centuries! It originated as a way to preserve fish using fermented rice.',
    difficulty: 1,
    emoji: '🍣',
  },
  {
    id: 'food-mx',
    category: 'FOOD',
    country: 'Mexico',
    flag: '🇲🇽',
    destination: 'Mexico',
    bgFrom: '#006847',
    bgTo: '#ce1126',
    question: 'What is the name of the Mexican dish with folded tortilla filled with meat and cheese?',
    options: ['Burrito', 'Taco', 'Enchilada', 'Quesadilla'],
    correctIndex: 1,
    explanation: 'Tacos are one of Mexico\'s most beloved foods! In Mexico City, people eat tacos at breakfast, lunch, and dinner.',
    difficulty: 1,
    emoji: '🌮',
  },
  {
    id: 'food-in',
    category: 'FOOD',
    country: 'India',
    flag: '🇮🇳',
    destination: 'India',
    bgFrom: '#ff9933',
    bgTo: '#8b0000',
    question: 'What is the name of the Indian bread baked in a clay oven called a tandoor?',
    options: ['Roti', 'Naan', 'Chapati', 'Pita'],
    correctIndex: 1,
    explanation: 'Naan is a leavened flatbread cooked in a tandoor oven. It\'s perfect for scooping up delicious curries!',
    difficulty: 2,
    emoji: '🍞',
  },
  {
    id: 'food-fr',
    category: 'FOOD',
    country: 'France',
    flag: '🇫🇷',
    destination: 'France',
    bgFrom: '#002395',
    bgTo: '#ed2939',
    question: 'What is the name of the long, thin French bread?',
    options: ['Ciabatta', 'Focaccia', 'Baguette', 'Brioche'],
    correctIndex: 2,
    explanation: 'The French baguette is so important to French culture that its recipe is protected by law! The French eat 30 million baguettes every day.',
    difficulty: 1,
    emoji: '🥖',
  },
  {
    id: 'food-th',
    category: 'FOOD',
    country: 'Thailand',
    flag: '🇹🇭',
    destination: 'Thailand',
    bgFrom: '#a51931',
    bgTo: '#2d2a4a',
    question: 'What is the name of Thailand\'s most famous noodle dish?',
    options: ['Pho', 'Pad Thai', 'Ramen', 'Lo Mein'],
    correctIndex: 1,
    explanation: 'Pad Thai is stir-fried rice noodles with eggs, tofu or shrimp, and peanuts. It\'s the national dish of Thailand!',
    difficulty: 2,
    emoji: '🍜',
  },
  {
    id: 'food-sp',
    category: 'FOOD',
    country: 'Spain',
    flag: '🇪🇸',
    destination: 'Spain',
    bgFrom: '#c60b1e',
    bgTo: '#ffc400',
    question: 'What Spanish rice dish is cooked with saffron and seafood or meat?',
    options: ['Risotto', 'Paella', 'Pilaf', 'Biryani'],
    correctIndex: 1,
    explanation: 'Paella originated in Valencia, Spain! The name comes from the wide, flat pan it\'s cooked in.',
    difficulty: 2,
    emoji: '🥘',
  },

  // === FLAGS ===
  {
    id: 'flag-ca',
    category: 'FLAG',
    country: 'Canada',
    flag: '🇨🇦',
    destination: 'Canada',
    bgFrom: '#ff0000',
    bgTo: '#8b0000',
    question: 'Which country has a red maple leaf on its flag?',
    options: ['Japan', 'Canada', 'Switzerland', 'Denmark'],
    correctIndex: 1,
    explanation: 'Canada\'s flag features a red maple leaf, which has been a symbol of Canada since the 18th century!',
    difficulty: 1,
    emoji: '🍁',
  },
  {
    id: 'flag-jp',
    category: 'FLAG',
    country: 'Japan',
    flag: '🇯🇵',
    destination: 'Japan',
    bgFrom: '#bc0004',
    bgTo: '#ff9999',
    question: 'Japan\'s flag features a red circle on a white background. What does the red circle represent?',
    options: ['The Moon', 'The Sun', 'Mount Fuji', 'Cherry Blossom'],
    correctIndex: 1,
    explanation: 'Japan\'s flag is called "Hinomaru" meaning "Circle of the Sun." Japan is known as "The Land of the Rising Sun"!',
    difficulty: 1,
    emoji: '☀️',
  },
  {
    id: 'flag-br',
    category: 'FLAG',
    country: 'Brazil',
    flag: '🇧🇷',
    destination: 'Brazil',
    bgFrom: '#009c3b',
    bgTo: '#002776',
    question: 'What shape is in the center of Brazil\'s green and yellow flag?',
    options: ['Triangle', 'Star', 'Circle (Blue globe)', 'Diamond'],
    correctIndex: 2,
    explanation: 'Brazil\'s flag has a blue globe with stars representing Brazilian states and the motto "Order and Progress"!',
    difficulty: 2,
    emoji: '⭐',
  },
  {
    id: 'flag-gr',
    category: 'FLAG',
    country: 'Greece',
    flag: '🇬🇷',
    destination: 'Greece',
    bgFrom: '#0d5eaf',
    bgTo: '#ffffff',
    question: 'How many blue and white stripes are on the Greek flag?',
    options: ['7', '9', '11', '13'],
    correctIndex: 1,
    explanation: 'Greece\'s flag has 9 horizontal stripes — 5 blue and 4 white. The 9 stripes represent the 9 syllables in "Freedom or Death"!',
    difficulty: 3,
    emoji: '🏛️',
  },
];

export function getQuestions(difficulty?: Difficulty, category?: Category): Question[] {
  let filtered = questions;
  if (difficulty) filtered = filtered.filter((q) => q.difficulty === difficulty);
  if (category) filtered = filtered.filter((q) => q.category === category);
  return filtered;
}

export function getRandomQuestions(count: number, difficulty?: Difficulty): Question[] {
  const pool = getQuestions(difficulty);
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getAllQuestions(): Question[] {
  return questions;
}

export const GESTURE_BONUS_ROUNDS = [
  {
    id: 'bonus-1',
    instruction: 'Show THREE fingers to select Europe!',
    requiredGesture: 'THREE_FINGERS',
    emoji: '✌️',
    points: 20,
  },
  {
    id: 'bonus-2',
    instruction: 'Give a THUMBS UP if you love exploring the world!',
    requiredGesture: 'THUMBS_UP',
    emoji: '👍',
    points: 15,
  },
  {
    id: 'bonus-3',
    instruction: 'Show an OPEN PALM to sail across the ocean!',
    requiredGesture: 'OPEN_PALM',
    emoji: '✋',
    points: 15,
  },
];
